name: Docker Image Builder

on:
  workflow_run:
    workflows: ["Security Scan Before Docker Build"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout the repo
      uses: actions/checkout@v3

    # 2. Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    # 3. Set up QEMU
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
  
    # 4. Set up Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 5. Build & Push image
    - name: Build and Push Image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest
